Added Projects-page
MichalPorag/pull-request-community pull request #121
Opened 2022-01-05 16:37 UTC by InbarDanieli

adding page for mentor's projects

2022-01-05 18:39 UTC, MichalPorag requested changes
Great job! you did quite a lot in one day! just a few changes, please look at the comments  :)

2022-01-05 18:39 UTC, MichalPorag commented on pages/projects/vest.tsx
> +    <div>
please change to fregment

2022-01-05 18:39 UTC, MichalPorag commented on pages/projects/vest.tsx
> +        <div className={style.star}>
please use before/ after (on the number of stars element) to create the star element

2022-01-05 18:39 UTC, MichalPorag commented on pages/projects/vest.tsx
> +          <div className={style.starText}>30K</div>
please move it to be a child of the title

2022-01-05 18:39 UTC, MichalPorag commented on pages/projects/vest.tsx
> +        <h3 className={style.title}>Vest</h3>
please use flexbox to center the title

2022-01-05 18:39 UTC, MichalPorag commented on styles/projects.module.scss
> +  background-image: url("../public/Star\ 1.svg");
please try to use shortcuts

2022-01-05 18:39 UTC, MichalPorag commented on styles/projects.module.scss
> +  font-style: normal;
please remove no needed styles

2022-01-05 18:39 UTC, MichalPorag commented on pages/projects/vest.tsx
> +    <div>
please move project page to a component that we can use later in more cases

2022-01-06 17:05 UTC, InbarDanieli commented on styles/projects.module.scss
> +  background-image: url("../public/Star\ 1.svg");
what do you mean by shortcuts?

2022-01-09 11:48 UTC, MichalPorag approved these changes

2022-01-09 11:50 UTC, merged